### ISSUE TITLE
removeAction does not exist in the latest build

### ISSUE THREAD

**Issue by DVLP** [kripken/ammo.js#101]
in previous ammo there was addVehicle which was now replaced by addAction
removeVehicle was also removed, but removeAction is missing

**Comment by lo-th** [comment]
yes need to add world.removeAction( car );
Ammo.destroy( car ); don't work

**Comment by kripken** [comment]
Could we have a pull request with those additions to the main repo?

**Comment by lo-th** [comment]
mm your version don't include terrainshape 
i'm on big demo to see all ammo possibility with live editor

**Comment by DVLP** [comment]
@kripken Yes, but what about "applyLocalTorque" or "applyCentralLocalForce". These are my new functions which I've added directly to bullet so they might disappear when updating bullet. How to solve this properly? These are must-haves when programming helicopters and airplanes (yaw, pitch  roll), but not natively available in bullet.

**Comment by lo-th** [comment]
maybe use quaterion transform for that but is a interesting demo to test

**Comment by DVLP** [comment]
Nice demo, 1000 objects are still working good. This guy added ammo to three.js editor, but I don't see the source for it: https://www.youtube.com/watch?v=Y4ygcI6HSW4

**Comment by DVLP** [comment]
@kripken pull request created. These functions are used to set forces locally and are not only specific to ammo.js. For some reason bullet does not have them and every time you want to set local force you have to make calculations and apply global forces. These are much more intuitive: applyLocalTorque is for setting for yaw pitch and roll forces. applyLocalCentralForce is to set for local X, Y and Z forces.
@lo-th Yeah, life's good.

**Comment by lo-th** [comment]
not yet
but is provided in the advanced demos of my ammo.lab

**Comment by lo-th** [comment]
here the terrain/car preview
http://lo-th.github.io/Ammo.lab/#terrain 
many options and control come next

**Comment by lo-th** [comment]
New add is great thank's
now i have all function for cool demo

**Comment by DVLP** [comment]
You're welcome. On what new cool demo are you working on?

**Comment by lo-th** [comment]
i add next demos to 
http://lo-th.github.io/Ammo.lab/
i have to complete worker and make better 3d look 
(click on demo name on top left for switch demo)

**Comment by DVLP** [comment]
I like this editor. Fast and nice design. I'd change the dot to an arrow in upper left corner. Now it's not obvious that there's a dropdown there, but looks like a title.
removeAction problem is now fixed and closing.
