### ISSUE TITLE
setCcdMotionThreshold and setCcdSweptSphereRadius

### ISSUE THREAD

**Issue by Bunzaga** [kripken/ammo.js#102]
It says setCcdMotionThreshold and setCcdSweptSphereRadius were added to the IDL 10-10-2014, yet it isn't in the latest build?

I've tried to build ammo.js myself, but keep getting errors with Emscripten 1.29.0.  It can't seem to find my EMSCRIPTEN_ROOT, even though it is in my system path.

Anyway, can you please update the ammo.js build?

**Comment by kripken** [comment]
I pushed an updated build now.

**Comment by Bunzaga** [comment]
Awesome!  Thank you very much.
