### ISSUE TITLE
Errors building ammo.js

### ISSUE THREAD

**Issue by mbrazell** [kripken/ammo.js#107]
I'm trying to build ammo.js, so that I can add setGravity() to rigid bodies.  I'm getting the following errors when I run python make.py:

>python make.py

--------------------------------------------------
Building ammo.js, build type: ['-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=
1', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '
--memory-init-file', '0', '-s', 'NO_FILESYSTEM=1', '-s', 'NO_BROWSER=1', '-s', '
TOTAL_MEMORY=67108864']
--------------------------------------------------

==========================
Stage 1: Generate bindings
==========================

Traceback (most recent call last):
  File "C:/Program Files/Emscripten/emscripten/1.29.0\tools\webidl_binder.py", line 36, in <module>
    data = p.finish()
  File "C:\Program Files\Emscripten\emscripten\1.29.0\third_party\WebIDL.py", line 4975, in finish
    production.finish(self.globalScope())
  File "C:\Program Files\Emscripten\emscripten\1.29.0\third_party\WebIDL.py", line 629, in finish
    member.finish(scope)
  File "C:\Program Files\Emscripten\emscripten\1.29.0\third_party\WebIDL.py", line 3310, in finish
    returnType = returnType.complete(scope)
  File "C:\Program Files\Emscripten\emscripten\1.29.0\third_party\WebIDL.py", line 1469, in complete
    [self.location])
WebIDL.WebIDLError: error: Unresolved type '<unresolved scope>::btScalar'., <unknown> line 124:10
  [Const] btScalar getDistance();
          ^
Traceback (most recent call last):
  File "make.py", line 85, in <module>
    assert os.path.exists('glue.js')
AssertionError

Any ideas on what I'm doing wrong?  I have the latest from github.  

Alternatively, is there any way I can simulate setGravity() without having to build?

For context, I'm trying to detect collision for a selected object (one that I move with my mouse), so I don't want it responding to gravity between simulation steps.

Sincerest thanks.

**Comment by kripken** [comment]
Latest which branch? On incoming it works for me. But I think master should work too.

Does the emscripten `test_webidl` test pass? (`tests/runner.py test_webidl`)

**Comment by mbrazell** [comment]
This is the result of runner.py test_webidl:

C:\inetpub\wwwroot\emscripten-incoming\tests>python runner.py test_webidl
test_webidl (test_core.default) ... (checking sanity from test runner)
WARNING  root: (Emscripten: system change:
1.32.1|asmjs-unknown-emscripten|C:/Pr
ogram Files/Emscripten/clang/e1.30.0_64bit|3.5 vs
1.32.0|asmjs-unknown-emscripte
n|C:/Program Files/Emscripten/clang/e1.30.0_64bit|3.5, clearing cache)
WARNING  root: LLVM version appears incorrect (seeing "3.5", expected "3.6")
ERROR    root: Emscripten, llvm and clang versions do not match, this is
dangero
us (1.32.1, 1.30.0, 1.30.0)
ERROR    root: Make sure to use the same branch in each repo, and to be
up-to-da
te on each. See
http://kripken.github.io/emscripten-site/docs/building_from_sour
ce/LLVM-Backend.html
INFO     root: (Emscripten: Running sanity checks)
testing mode ALL
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\emscripten-incoming\emscripten.py", line 1043,
in <mo
dule>
    _main(environ=os.environ)
  File "C:\inetpub\wwwroot\emscripten-incoming\emscripten.py", line 1033,
in _ma
in
    temp_files.run_and_clean(lambda: main(
  File "C:\inetpub\wwwroot\emscripten-incoming\tools\tempfiles.py", line
39, in
run_and_clean
    return func()
  File "C:\inetpub\wwwroot\emscripten-incoming\emscripten.py", line 1039,
in <la
mbda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "C:\inetpub\wwwroot\emscripten-incoming\emscripten.py", line 940, in
main

    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "C:\inetpub\wwwroot\emscripten-incoming\emscripten.py", line 261, in
emsc
ript
    asm_consts = [0]*len(metadata['asmConsts'])
KeyError: 'asmConsts'
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\emscripten-incoming\emcc", line 1263, in <module>
    final = shared.Building.emscripten(final, append_ext=False,
extra_args=extra
_args)
  File "C:\inetpub\wwwroot\emscripten-incoming\tools\shared.py", line 1534,
in e
mscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to
generate .j
s'
AssertionError: Emscripten failed to generate .js
FAIL: Running the generated program failed!
FAIL

======================================================================
FAIL: test_webidl (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\emscripten-incoming\tests\test_core.py", line
6675, i
n test_webidl
    do_test_in_mode('ALL')
  File "C:\inetpub\wwwroot\emscripten-incoming\tests\test_core.py", line
6673, i
n do_test_in_mode
    output_nicerizer=(lambda out, err: out))
  File "C:\inetpub\wwwroot\emscripten-incoming\tests\runner.py", line 464,
in do
_run
    build_ll_hook=build_ll_hook,
extra_emscripten_args=extra_emscripten_args, po
st_build=post_build)
  File "C:\inetpub\wwwroot\emscripten-incoming\tests\runner.py", line 239,
in bu
ild
    assert 'memory initializer */' in src or '/*' not in src # memory
initialize
r comment, or cleaned-up source with no comments
AssertionError

----------------------------------------------------------------------
Ran 1 test in 19.142s

FAILED (failures=1)

**Comment by kripken** [comment]
As the error message says, something is wrong in your setup. Can follow

http://kripken.github.io/emscripten-site/docs/building_from_source/building_fastcomp_manually_from_source.html?highlight=fastcomp

or use the SDK.

**Comment by mbrazell** [comment]
Alon:

I've tried to follow the instructions for building fastcomp, and have the
following errors:

If I attempt to build with -G "Visual Studio 10 Win64", I get:

MSVCRTD.lib(crtexe.obj) : fatal error LNK1112: module machine type 'IA64' co
nflicts with target machine type 'x64'
[C:\inetpub\wwwroot\fastcomp\emscripten-f
astcomp\build\CMakeFiles\CMakeTmp\cmTryCompileExec3819444703.vcxproj]

And if I attempt to build without that option, I get:

testCCompiler.obj : error LNK2001: unresolved external symbol
  __RTC_Shutdown

[C:\inetpub\wwwroot\fastcomp\emscripten-fastcomp\build\CMakeFiles\CMakeTmp\cmT
ryCompileExec4008830393.vcxproj]


  testCCompiler.obj : error LNK2001: unresolved external symbol
  __RTC_InitBase

[C:\inetpub\wwwroot\fastcomp\emscripten-fastcomp\build\CMakeFiles\CMakeTmp\cmT
ryCompileExec4008830393.vcxproj]


  LINK : error LNK2001: unresolved external symbol _mainCRTStartup

[C:\inetpub\wwwroot\fastcomp\emscripten-fastcomp\build\CMakeFiles\CMakeTmp\cmT
ryCompileExec4008830393.vcxproj]

I'm sincerely trying to follow the instructions but have hit a wall here.
Any guidance would be greatly appreciated.

**Comment by kripken** [comment]
I don't know much about windows. Perhaps @juj can help. But, perhaps just use the SDK instead of compiling from source?

**Comment by juj** [comment]
The issue seems to be that somehow it's picking up Itanium 64-bit build target instead of the widespread (AMD) x64 64-bit target. Also, you should use VS2012 or VS2013 to build, VS2010 is no longer supported in LLVM 3.4 and newer.

Best recommendation is to use emsdk - it can either use a prebuilt version of the compiler, or build the compiler from scratch (effectively it automates the cmdline instructions you'd be typing manually) from either the master or incoming branches, using either VS2012 or VS2013.

**Comment by mbrazell** [comment]
I initially tried the latest SDK installer (emsdk-1.29.0-web-64bit.exe), but that gives me the LLVM version out of date (3.3 instead of 3.6) when I run the "tests/runner.py test_webidl" on emscripten incoming.

**Comment by mbrazell** [comment]
I was able to successfully build emscripten on my Mac.  The runner.py test succeeds.  However, now I am trying to build ammo.js, and am getting the following (I've already run autogen.sh):

VB-70:ammo.js mbrazell$ python make.py

--------------------------------------------------
Building ammo.js, build type: ['-O3', '--llvm-lto', '1', '-s', 'NO_EXIT_RUNTIME=1', '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1', '-s', 'NO_DYNAMIC_EXECUTION=1', '--memory-init-file', '0', '-s', 'NO_FILESYSTEM=1', '-s', 'NO_BROWSER=1', '-s', 'TOTAL_MEMORY=67108864', '-s', 'EXPORT_NAME="AmmoLib"', '-s', 'MODULARIZE=1']
--------------------------------------------------


==========================
Stage 1: Generate bindings
==========================


=======================
Stage 2: Build bindings
=======================


===================================================================
Stage 3: Configure (if this fails, run autogen.sh in bullet/ first)
===================================================================

checking build system type... x86_64-apple-darwin14.0.0
checking host system type... x86_64-apple-darwin14.0.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ../install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... /Users/mbrazell/emsdk/emscripten/incoming/emcc
checking whether the C compiler works... no
configure: error: in `/Users/mbrazell/GitHub/ammo.js/bullet/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR    root: Configure step failed with non-zero return code 77! Command line: ['../configure', '--disable-demos', '--disable-dependency-tracking'] at /Users/mbrazell/GitHub/ammo.js/bullet/build
Traceback (most recent call last):
  File "make.py", line 101, in <module>
    emscripten.Building.configure(['../configure', '--disable-demos','--disable-dependency-tracking'])
  File "/Users/mbrazell/emsdk/emscripten/incoming/tools/shared.py", line 1105, in configure
    raise subprocess.CalledProcessError(cmd=args, returncode=process.returncode)
subprocess.CalledProcessError: Command '['../configure', '--disable-demos', '--disable-dependency-tracking']' returned non-zero exit status 77

**Comment by juj** [comment]
Ops, very sorry, the download links in the docs were stale, I forgot to update them! (did so now: https://github.com/kripken/emscripten/commit/9b5b12aa701460f75b43d1639ea95425e6723c40). The official announcement for 1.30.0 release was in the mailing list at https://groups.google.com/forum/#!topic/emscripten-discuss/b06iW6T2uSw . If you want to use the latest incoming branch, you can run `emsdk install sdk-incoming-64bit` to get the most recent development version.

**Comment by juj** [comment]
Hmm, not sure what goes wrong there, though I think it might be necessary to skip the configure script from attempting to run the "executables" it builds, since the outputs are .js files and not natively executable. Not completely sure if that's the case though, I'm not super-familiar with Unix configure scripts. @kripken : can you recall having a similar error?

**Comment by mbrazell** [comment]
Thank you for your assistance @juj.  I will download the latest and reinstall.  Hopefully @kripken has an idea about the configure script attempting to run executables.  I appreciate the help from both of you!

**Comment by kripken** [comment]
The configure script probably has the error details in `config.log`.

**Comment by mbrazell** [comment]
I believe I'm experiencing the same problem as described in
http://comments.gmane.org/gmane.comp.compilers.emscripten/4973.

It seems the solution was to add EMCONFIGURE_JS=1.  I've tried adding this
to the bullet/configure file, but with no luck.  Is this where I should be
placing it?  If so, does it matter where?

My config.log contains these errors:

configure:3271: checking for C compiler version
configure:3280: /Users/mbrazell/emsdk/emscripten/incoming/emcc --version >&5
env: python2: No such file or directory
configure:3291: $? = 127
configure:3280: /Users/mbrazell/emsdk/emscripten/incoming/emcc -v >&5
env: python2: No such file or directory
configure:3291: $? = 127
configure:3280: /Users/mbrazell/emsdk/emscripten/incoming/emcc -V >&5
env: python2: No such file or directory
configure:3291: $? = 127
configure:3280: /Users/mbrazell/emsdk/emscripten/incoming/emcc -qversion >&5
env: python2: No such file or directory
configure:3291: $? = 127
configure:3311: checking whether the C compiler works
configure:3333: /Users/mbrazell/emsdk/emscripten/incoming/emcc
 conftest.c  >&5
env: python2: No such file or directory
configure:3337: $? = 127
configure:3375: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "bullet"
| #define PACKAGE_TARNAME "bullet"
| #define PACKAGE_VERSION "2.82"
| #define PACKAGE_STRING "bullet 2.82"
| #define PACKAGE_BUGREPORT "erwin.coumans@gmail.com"
| #define PACKAGE_URL ""
| #define PACKAGE "bullet"
| #define VERSION "2.82"
| /* end confdefs.h.  */

Thank you for your continued support.

**Comment by mbrazell** [comment]
I also tried adding EMCONFIGURE_JS=1 to the emcc_args in make.py, again no luck.

**Comment by mbrazell** [comment]
I found the initial error was the /usr/bin/env python2 needed to be /usr/bin/python.  This has gotten me much farther, the latest error is:

conftest.c:11:10: fatal error: 'ac_nonexistent.h' file not found
#include <ac_nonexistent.h>

any ideas on this one?

Thanks.

**Comment by mbrazell** [comment]
I've gotten past several hurdles.  The latest error I'm getting is:

configure:15697: checking whether byte ordering is bigendian
configure:15712: /Users/mbrazell/emsdk/emscripten/incoming/emcc -c   conftest.c >&5
conftest.c:26:9: error: unknown type name 'not'
               not a universal capable compiler
               ^
conftest.c:26:14: error: expected ';' after top level declarator
               not a universal capable compiler
                    ^
                    ;
2 errors generated.

I'm using a Mac.

**Comment by mbrazell** [comment]
Believe it or not I just got it to work... thank you so much for your help!

**Comment by kripken** [comment]
`EMCONFIGURE_JS` is an environment variable, so `EMCONFIGURE_JS=1 python make.py` etc. should work.

**Comment by mbrazell** [comment]
Alon:

I was able to successfully compile last night, and the build is working
well.  I now plan on adding setGravity to rigid body.  Thanks again for
your help!

Michael

**Comment by mbrazell** [comment]
https://drive.google.com/file/d/1N7dTW2wcUbvpZRTiQqXXMvMwDwoYNbDUdg/edit?usp=docslist_api
