### ISSUE TITLE
How to determine which Bullet features are currently available in Ammo?

### ISSUE THREAD

**Issue by josephrocca** [kripken/ammo.js#118]
I'm seriously considering moving a large project over to Ammo, but I'd like to be 100% sure that all of the Bullet features I need have been ported. I'm not familiar with emscripten at all, so I really have no idea how to check this.

Is there some way to check which Bullet features are currently available in Ammo? Something to do with Ctrl+F and `ammo.idl` maybe?

Thanks

**Comment by kripken** [comment]
Yes, exactly the things in `ammo.idl` are what is available.

It's easy to add more as needed, if we are missing something, let us know and/or send a PR.

Also very easy to remove something from the IDL if you don't need it and want a smaller custom build.

**Comment by josephrocca** [comment]
Great! Thanks :)
