### ISSUE TITLE
Terrain implementation

### ISSUE THREAD

**Issue by yomboprime** [kripken/ammo.js#120]
I've implemented btHeightfieldTerrainShape and have it working.
You can see the changes to the IDL [here](https://github.com/yomboprime/ammo.js/commit/a8352928bb282de6f6074ba75ae526db867cc0d8)

Should I make a web example before posting a PR? I can make it in Three.js (graphics library)

**Comment by kripken** [comment]
PR first is fine. But a demo would be nice to see of course.

**Comment by yomboprime** [comment]
All right, I'll start to add the demo.

**Comment by lo-th** [comment]
that's great !!!

**Comment by yomboprime** [comment]
Thanks Io-th!
Closing the issue as PR is merged.
