### ISSUE TITLE
Adding btSoftBodyHelpers::CreateFromTriMesh

### ISSUE THREAD

**Issue by yomboprime** [kripken/ammo.js#130]
I'm trying to add to the IDL the function `CreateFromTriMesh` of `btSoftBodyHelpers.h`.

The problem is that it has two parameters of C array type: `float *vertices` and `int *triangles`
```
btSoftBody CreateFromTriMesh([Ref] btSoftBodyWorldInfo worldInfo, float* vertices, int* triangles, long ntriangles, boolean randomizeConstraints);
```
I've tried the following for example for the `float *` parameter:
```
VoidPtr vertices
any vertices
float[] vertices
[Ref] float vertices
```
All give compile errors, of not being able to convert the parameter to `float *`. Any help on how to do that?

**Comment by kripken** [comment]
What is the full error message? What is it trying to convert from, into `float*`?

**Comment by yomboprime** [comment]
If I try with `voidPtr` or with `any`, the message is:
`glue.cpp:3647:41: error: cannot initialize a parameter of type 'const btScalar *' (aka 'const float *') with an lvalue of type 'void *'`

With `float[]`:
`glue.cpp:3647:41: error: cannot initialize a parameter of type 'const btScalar *' (aka 'const float *') with an lvalue of type 'float'`

With `[ref] float`:
`glue.cpp:3647:41: error: indirection requires pointer operand ('float' invalid)`

**Comment by kripken** [comment]
I see, thanks. Ok, this looks like a current limitation of the webidl binder. Looking into it now to see how feasible it is to add.

**Comment by yomboprime** [comment]
Thanks! If I could help...

**Comment by kripken** [comment]
Ok, emscripten incoming now has support for this, see an example in https://github.com/kripken/emscripten/commit/7b4069e4f517fa58d4c2a449fc840f2af22d21b5

**Comment by yomboprime** [comment]
Thanks! Checking out...

**Comment by yomboprime** [comment]
This is great! It compiles now. Will need some time to make a demo showing volumetric soft bodies (helped by Lo Th)

**Comment by kripken** [comment]
Great, looking forward to the demo!
