### ISSUE TITLE
Bullet callbacks

### ISSUE THREAD

**Issue by xpenatan** [kripken/ammo.js#133]
How can I create a callback listener so bullet call it ? 

For example, in c++ bullet. when you create a class that extend btMotionState, override getWorldTransform/setWorldTransform and set it to a btRigidBody#setMotionState( ...)  bullet will first call getWorldTransform and when the rigid body moves it will call setWorldTransform(..).  setWorldTransform is used to update models position.  How can this work with ammo and emscripten? 

I tried option 1 by doing this:
```
  var motionState = new Ammo.myMotionState();
		
  motionState.getWorldTransform = function(worldTrans1) { 
      alert("111");
  };
  motionState.setWorldTransform = function(worldTrans2) { 
      alert("222");
  };
   rBody.setMotionState(motionState);

```
myMotionState is a c++ class i made that extends c++ btMotionState. I have this in ammo.idl file
```
 interface myMotionState {
   void myMotionState();
 };
 myMotionState implements btMotionState;
```
but it don't work.
I also tried option 2: https://github.com/kripken/ammo.js/blob/master/ammo.idl#L146-L150 and https://github.com/kripken/ammo.js/blob/master/tests/wrapping.js#L71-L81 but it also dont call alert.

And there is option 3: https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html     Its similar to option 1 for creating a c++ file. Do I actually need to create a c++? 
if option 3 is the only working solution. which one is the best one?  possible to have a example to call motionState.getWorldTransform  and motionState.setWorldTransform  methods with btTransform parameter?   

There is more callback like this in bullet, making this work will also help when implementing the other ones. 

Option2 is the best one because I can just edit the idl file without touching c++. Am I missing something?

**Comment by kripken** [comment]
I think what we use here is JSImplementation stuff in the ammo.idl file. For example ConcreteContactResultCallback. See tests/wrapping.js.

**Comment by xpenatan** [comment]
Wow, that was a fast reply. I tried with JSImplementation  (option 2) by doing this 

```
var motionState = new $wnd.Ammo.testMotionState();
		
motionState .getWorldTransform = function(worldTrans1) { 
  $wnd.alert("111");
};
motionState .setWorldTransform = function(worldTrans2) { 
  $wnd.alert("222");
};
```		

```
[JSImplementation="myMotionState"]
interface testMotionState {
  void testMotionState();
  void getWorldTransform([Ref] btTransform worldTrans);
  void setWorldTransform([Ref] btTransform worldTrans);
};
```
I also tried by using btDefaultMotionState by it still alert is not being called by bullet.

In the wrapping.js example, the method is called manually by the function and not by bullet.

**Comment by kripken** [comment]
See `test_webidl` in the emscripten repo, it should test what you want (runVirtualFunc, etc.), and it passes. (test logic is in tests/test_core.py)

**Comment by xpenatan** [comment]
@kripken I managed to get working with btDefaultMotionState and myMotionState c++ class but still there is one problem left.  I cannot compile 
```
[JSImplementation="btMotionState"]
interface testMotionState {
  void testMotionState();
  void getWorldTransform([Ref] btTransform worldTrans);
  void setWorldTransform([Const, Ref] btTransform worldTrans);
};
```
![compile erro](https://cloud.githubusercontent.com/assets/6472084/12187551/ffcf5078-b593-11e5-92c6-0c58711439f6.png)

I can only compile if I modify btMotionState.h to have a body. 
```
virtual void	getWorldTransform(btTransform& worldTrans )
{
}
virtual void	setWorldTransform(const btTransform& worldTrans)
{
}
```


the default is:
```
virtual void	getWorldTransform(btTransform& worldTrans ) const =0;
virtual void	setWorldTransform(const btTransform& worldTrans)=0;
```

**Comment by kripken** [comment]
How about if you implement `btDefaultMotionState` instead? Seems to build over here.

It might be good for the webidl binder to support abstract base classes, but it's not a simple thing to add, I suspect.

**Comment by xpenatan** [comment]
Oh, so its because its not supported. Thats ok then. I''ll just modify all bullet c++ callbacks to have a body (if there is more like this).  Thanks for your time. Sorry for bothering you.
