### ISSUE TITLE
Uncaught ReferenceError: _emscripten_bind_btGeneric6DofConstraint_btGeneric6DofConstraint_4 is not defined

### ISSUE THREAD

**Issue by sasha240100** [kripken/ammo.js#140]
Console:

```console
Uncaught ReferenceError: _emscripten_bind_btGeneric6DofConstraint_btGeneric6DofConstraint_4 is not defined
```

I have found only 1 _emscripten_bind_btGeneric6DofConstraint_btGeneric6DofConstraint_4 in ammo.js
Where others?

**Comment by ButzYung** [comment]
I ran into the same problem. I wonder if anyone has a solution.

**Comment by sasha240100** [comment]
@ButzYung Solved that with adding 4th parameter `ammo.btGeneric6DofConstraint`
