### ISSUE TITLE
world. addVehicle is missing ?

### ISSUE THREAD

**Issue by jeromeetienne** [kripken/ammo.js#147]
im trying to add a vehicule in my world. but ammo.js discrete world doesent seems to have it.

What i am missing ?

Here is the docs for this function in bullet. 
http://bulletphysics.org/Bullet/BulletFull/classbtDiscreteDynamicsWorld.html#a331ec28128a2ff57f8efa78171dfccfa

**Comment by willeastcott** [comment]
addVehicle was deprecated in Bullet in favour of addAction

**Comment by jeromeetienne** [comment]
thanks
