### ISSUE TITLE
How to create Kinematic Bodies

### ISSUE THREAD

**Issue by ValSergey** [kripken/ammo.js#150]
btCollisionObject::CF_KINEMATIC_OBJECT ?

**Comment by willeastcott** [comment]
If it helps, here's how PlayCanvas creates bodies (including kinematic bodies):

https://github.com/playcanvas/engine/blob/18bdc36d108031beca3fbfab948feb911eea2159/src/framework/components/rigid-body/component.js#L135

**Comment by ValSergey** [comment]
Ok!
CF_KINEMATIC_OBJECT= 2

**Comment by willeastcott** [comment]
Yep. 👍
