### ISSUE TITLE
Offset does not work properly

### ISSUE THREAD

**Issue by 1O1111** [kripken/ammo.js#160]
Trying to apply an offset to motion state by using  btDefaultMotionState(startTrans,centerOfMassOffset) or motionstate->m_centerOfMassOffset=centerOfMassOffset does not seem to work properly on the emscripten port.

**Comment by lo-th** [comment]
you have to use compound shape

var massCenter = new Ammo.btVector3( 0, 20, 0);
var compound = new Ammo.btCompoundShape();
compound.addChildShape( massCenter, shape );

**Comment by 1O1111** [comment]
But the native version of bullet works fine with both rotational and linear offset without using btcompoundshape . This seems to be bug in the implementation of bullet in emscripten.
ps: I am aware of btcompoundshape and use it when necessary.

**Comment by 1O1111** [comment]
Fixed it by changing centerOfMassWorldTrans defaultmotionstate header file from (m_centerOfMassOffset.inverse() * m_graphicsWorldTrans) to 
(m_graphicsWorldTrans * m_centerOfMassOffset.inverse()).
