### ISSUE TITLE
setActivationState always disables

### ISSUE THREAD

**Issue by DVLP** [kripken/ammo.js#161]
After updating ammo I noticed that any state other than 4 (DISABLE_DEACTIVATION) causes bodies to freeze in place. 

```
body.setActivationState(1); // 1 - active

body.activate();
```

this is a quick way to reproduce the problem. `body.activate();` is not helping. This can be a major problem with bigger scenes where object deactivation will never kick in while using 4(DISABLE_DEACTIVATION) on all objects.

**Comment by lo-th** [comment]
var STATE = {
    ACTIVE : 1,
    ISLAND_SLEEPING : 2,
    WANTS_DEACTIVATION : 3,
    DISABLE_DEACTIVATION : 4,
    DISABLE_SIMULATION : 5
}

with other than 4, if your object no move or no contact is freeze
