### ISSUE TITLE
Ammo.allocate is not a function

### ISSUE THREAD

**Issue by eezy0** [kripken/ammo.js#163]
Physijs_worker.js has encountered an error.

`var ptr = Ammo.allocate(4 * description.xpts * description.ypts, "float", Ammo.ALLOC_NORMAL);`

But ammo.js worked well in older versions.

**Comment by kripken** [comment]
I think we might have reduced the number of exported methods at some point, although I don't remember anything about `allocate` specifically. But, you can just do `Ammo.malloc(4 * description.xpts * description.ypts * 4)` (note the extra `*4`, since each float is 4 bytes). Does that work? It's more efficient than `allocate` anyhow.

**Comment by aleciavogel** [comment]
@kripken I am having the same issue as @eezy0 and they posted the same question in the [Physi.Js issue tracker](https://github.com/chandlerprall/Physijs/issues/294). 

When I implemented the snippet you provided above, I received an error that `Ammo.malloc is not a function`

**Comment by kripken** [comment]
Oh yes, it should be `Ammo._malloc` (with a prefix `_`, emscripten's convention for compiled methods).

**Comment by kegi** [comment]
Hi @kripken , look like ```Ammo._malloc``` is working but I have the same problem with ```Ammo.setValue```, is there a replacement for that method too ?

```typescript
const ptr: number = this.ammo._malloc(
    4 * mesh.nbPointsX * mesh.nbPointsY * 4,
    this.ammo.ALLOC_NORMAL,
)

mesh.values.forEach((value, index) => {
    this.ammo.setValue(ptr + index, value, 'float')
})
```

**Comment by kripken** [comment]
Think of it this way: each item in the HEAPF32 array is 4 bytes (a float32). So HEAPF32[0] covers "addresses" 0, 1, 2, and 3.

So you need to divide: To read the float at address 4, read `HEAPF32[1]` (which covers "addresses" 4, 5, 6, and 7).

I think `HEAPF32[ptr + (index * 4) >> 2]` is what you want here.

**Comment by kegi** [comment]
make a lot of sense, thx !
