### ISSUE TITLE
ammo.js no longer runs in Internet Explorer

### ISSUE THREAD

**Issue by willeastcott** [kripken/ammo.js#193]
Tested: IE11

I suspect this may be because ammo.js now relies on the presence of [Math.imul](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul) which is not supported in IE.

This is the line that IE11 gets upset about:

![image](https://user-images.githubusercontent.com/697563/38909915-a11e5534-427b-11e8-8293-f36f6d7ae725.png)

As you can see 'O' is Math.imul.

But in IE11:

![image](https://user-images.githubusercontent.com/697563/38909938-be037d5a-427b-11e8-86df-bc508fa75676.png)

I suspect this may be a general problem with Emscripten rather than ammo.js specifically, but I wasn't sure, so reporting here.

Note that [IE still accounts for >7% of desktop browser market share worldwide](http://gs.statcounter.com/browser-market-share/desktop/worldwide).

**Comment by kripken** [comment]
Thanks, yeah, we moved legacy browser support behind a flag in emscripten (`LEGACY_VM_SUPPORT`). Pushed that and updated builds.

**Comment by kripken** [comment]
How fast is ammo.js in IE11 btw? :)

**Comment by willeastcott** [comment]
Thanks for fixing this so quickly! ammo.js is not too shabby in IE11 actually. Perfectly reasonable perf. I get 28fps for the cloth example on my Win10 laptop in IE11.
