### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by swift502** [kripken/ammo.js#202]
Hi,
I'm trying to build ammo. I [set emscripten up](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#installation-instructions). The emscripten Hello world test compiled fine.

Then, when running `python make.py`, Stage 3 threw an error saying that mingw32-make is an unknown command. So I installed mingw32-make (I can't even understand what it's for...) but it still doesn't work because it doesn't have proper parameters...?

Any idea what I've done wrong?

```
==========================
Stage 1: Generate bindings
==========================


=======================
Stage 2: Build bindings
=======================


=============
Stage 3: Make
=============

mingw32-make: *** No targets specified and no makefile found.  Stop.
Traceback (most recent call last):
  File "make.py", line 173, in <module>
    build()
  File "make.py", line 133, in build
    emscripten.Building.make(['mingw32-make', '-j', str(CORES)])
  File "C:/Users/Username/Documents/GitHub/emsdk/emscripten/1.37.40\tools\shared.py", line 1569, in make
    raise subprocess.CalledProcessError(cmd=args, returncode=process.returncode)
subprocess.CalledProcessError: Command '['mingw32-make', '-j', '4']' returned non-zero exit status 2
```

**Comment by kripken** [comment]
That's something windows-specific, I guess? No idea on how to fix that. On linux though you need to run `./autogen.sh` manually in the bullet dir sometimes, perhaps that's related?

**Comment by swift502** [comment]
Thanks for a response.

Yeah I'm on Win10. I did run the autogen.sh but didn't notice it had errors as well. Now the autogen can't locate...
![image](https://user-images.githubusercontent.com/24359130/40266393-99f086e6-5b4a-11e8-8be6-7cb4204f2ebf.png)

I guess I need to add a reference to Config.pm to the @INC... thing, but apparently adding things to @INC is done using magic on Windows.

Would it be easier to just build ammo in an Ubuntu virtual machine? 😄

**Comment by kripken** [comment]
Probably, yeah... Ubuntu is where I build and test. Sorry for the inconvenience!

**Comment by JayceLai** [comment]
@swift502  Hello, do you have a successful compilation on the win10? I'm having the same problem right now.

**Comment by swift502** [comment]
@JayceLai I think I ended up installing [Cygwin](https://www.cygwin.com/) and then building Ammo there. Even then I still had several issues that I had to get over with trial and error, but eventually I made it. It's been a year though so I'm afraid I can't give you much detail...

**Comment by JayceLai** [comment]
> @JayceLai I think I ended up installing [Cygwin](https://www.cygwin.com/) and then building Ammo there. Even then I still had several issues that I had to get over with trial and error, but eventually I made it. It's been a year though so I'm afraid I can't give you much detail...
> 
> I wish you luck in building. 🙂 Though I'd like to note that I ended up using Cannon for my project, because Ammo didn't support physics callbacks of any sort at the time (not sure if it does now), and it was hell to iterate on the build with Cygwin. Cannon is native javascript and it's literally one console command to build it on windows.

 Thanks, I m trying to fix it
