### ISSUE TITLE
Custom Shape for imported 3d models

### ISSUE THREAD

**Issue by Carnaux** [kripken/ammo.js#208]
Hi, i'm trying to apply torque to a imported 3d model, but it is not working, and just torque, impulse and force are working. To create a rigidbody, while importing the 3d model, the code creates a shape based on the geometry of the 3d model to be able to simulate realistic collisions. 

  
     var triangle_mesh = new Ammo.btTriangleMesh();
        var triangles = [];
        var geometry = new THREE.Geometry().fromBufferGeometry( object.children[0].geometry );
        var vertices = geometry.vertices;
        var face;
        var _vec3_1 = new Ammo.btVector3(0, 0, 0);
        var _vec3_2 = new Ammo.btVector3(0, 0, 0);
        var _vec3_3 = new Ammo.btVector3(0, 0, 0);

        for ( var i = 0; i < geometry.faces.length; i++ ) {
          face = geometry.faces[i];
          if ( face instanceof THREE.Face3) {
    
            triangles.push([
              { x: vertices[face.a].x, y: vertices[face.a].y, z: vertices[face.a].z },
              { x: vertices[face.b].x, y: vertices[face.b].y, z: vertices[face.b].z },
              { x: vertices[face.c].x, y: vertices[face.c].y, z: vertices[face.c].z }
            ]);
    
          } else if ( face instanceof THREE.Face4 ) {
    
            triangles.push([
              { x: vertices[face.a].x, y: vertices[face.a].y, z: vertices[face.a].z },
              { x: vertices[face.b].x, y: vertices[face.b].y, z: vertices[face.b].z },
              { x: vertices[face.d].x, y: vertices[face.d].y, z: vertices[face.d].z }
            ]);
            triangles.push([
              { x: vertices[face.b].x, y: vertices[face.b].y, z: vertices[face.b].z },
              { x: vertices[face.c].x, y: vertices[face.c].y, z: vertices[face.c].z },
              { x: vertices[face.d].x, y: vertices[face.d].y, z: vertices[face.d].z }
            ]);
    
          }
        }
        
        for ( var i = 0; i < triangles.length; i++ ) {
          triangle = triangles[i];

          _vec3_1.setX(triangle[0].x );
          _vec3_1.setY(triangle[0].y );
          _vec3_1.setZ(triangle[0].z );
  
          _vec3_2.setX(triangle[1].x );
          _vec3_2.setY(triangle[1].y );
          _vec3_2.setZ(triangle[1].z );
  
          _vec3_3.setX(triangle[2].x );
          _vec3_3.setY(triangle[2].y );
          _vec3_3.setZ(triangle[2].z );
  
          triangle_mesh.addTriangle(
            _vec3_1,
            _vec3_2,
            _vec3_3,
            true
          );
        }

        var shape = new Ammo.btConvexTriangleMeshShape(
          triangle_mesh,
          true
        );
       
        return shape;
      }

Do you have any ideias on how to do so?

**Comment by aisriver** [comment]
it works for me!
`const getBufferGeometryShape = (geometry: THREE.BufferGeometry) => {
    const mesh = new AmmoLib.btTriangleMesh(true, true);
    const vertices = geometry.attributes.position?.array || [];
    const indices = geometry.index?.array || [];
    for (let i = 0; i * 3 < indices.length; i += 1) {
      mesh.addTriangle(
        new AmmoLib.btVector3(
          vertices[indices[i * 3] * 3],
          vertices[indices[i * 3] * 3 + 1],
          vertices[indices[i * 3] * 3 + 2]
        ),
        new AmmoLib.btVector3(
          vertices[indices[i * 3 + 1] * 3],
          vertices[indices[i * 3 + 1] * 3 + 1],
          vertices[indices[i * 3 + 1] * 3 + 2]
        ),
        new AmmoLib.btVector3(
          vertices[indices[i * 3 + 2] * 3],
          vertices[indices[i * 3 + 2] * 3 + 1],
          vertices[indices[i * 3 + 2] * 3 + 2]
        ),
        false
      );
    }
    const shape = new AmmoLib.btConvexTriangleMeshShape(mesh, true, true);
    return shape;
  };`

**Comment by aisriver** [comment]
> Hi, i'm trying to apply torque to a imported 3d model, but it is not working, and just torque, impulse and force are working. To create a rigidbody, while importing the 3d model, the code creates a shape based on the geometry of the 3d model to be able to simulate realistic collisions.
> 
> ```
>  var triangle_mesh = new Ammo.btTriangleMesh();
>     var triangles = [];
>     var geometry = new THREE.Geometry().fromBufferGeometry( object.children[0].geometry );
>     var vertices = geometry.vertices;
>     var face;
>     var _vec3_1 = new Ammo.btVector3(0, 0, 0);
>     var _vec3_2 = new Ammo.btVector3(0, 0, 0);
>     var _vec3_3 = new Ammo.btVector3(0, 0, 0);
> 
>     for ( var i = 0; i < geometry.faces.length; i++ ) {
>       face = geometry.faces[i];
>       if ( face instanceof THREE.Face3) {
> 
>         triangles.push([
>           { x: vertices[face.a].x, y: vertices[face.a].y, z: vertices[face.a].z },
>           { x: vertices[face.b].x, y: vertices[face.b].y, z: vertices[face.b].z },
>           { x: vertices[face.c].x, y: vertices[face.c].y, z: vertices[face.c].z }
>         ]);
> 
>       } else if ( face instanceof THREE.Face4 ) {
> 
>         triangles.push([
>           { x: vertices[face.a].x, y: vertices[face.a].y, z: vertices[face.a].z },
>           { x: vertices[face.b].x, y: vertices[face.b].y, z: vertices[face.b].z },
>           { x: vertices[face.d].x, y: vertices[face.d].y, z: vertices[face.d].z }
>         ]);
>         triangles.push([
>           { x: vertices[face.b].x, y: vertices[face.b].y, z: vertices[face.b].z },
>           { x: vertices[face.c].x, y: vertices[face.c].y, z: vertices[face.c].z },
>           { x: vertices[face.d].x, y: vertices[face.d].y, z: vertices[face.d].z }
>         ]);
> 
>       }
>     }
>     
>     for ( var i = 0; i < triangles.length; i++ ) {
>       triangle = triangles[i];
> 
>       _vec3_1.setX(triangle[0].x );
>       _vec3_1.setY(triangle[0].y );
>       _vec3_1.setZ(triangle[0].z );
> 
>       _vec3_2.setX(triangle[1].x );
>       _vec3_2.setY(triangle[1].y );
>       _vec3_2.setZ(triangle[1].z );
> 
>       _vec3_3.setX(triangle[2].x );
>       _vec3_3.setY(triangle[2].y );
>       _vec3_3.setZ(triangle[2].z );
> 
>       triangle_mesh.addTriangle(
>         _vec3_1,
>         _vec3_2,
>         _vec3_3,
>         true
>       );
>     }
> 
>     var shape = new Ammo.btConvexTriangleMeshShape(
>       triangle_mesh,
>       true
>     );
>    
>     return shape;
>   }
> ```
> 
> Do you have any ideias on how to do so?

it works for me!
```
const getBufferGeometryShape = (geometry: THREE.BufferGeometry) => {
    const mesh = new AmmoLib.btTriangleMesh(true, true);
    const vertices = geometry.attributes.position?.array || [];
    const indices = geometry.index?.array || [];
    for (let i = 0; i * 3 < indices.length; i += 1) {
      mesh.addTriangle(
        new AmmoLib.btVector3(
          vertices[indices[i * 3] * 3],
          vertices[indices[i * 3] * 3 + 1],
          vertices[indices[i * 3] * 3 + 2]
        ),
        new AmmoLib.btVector3(
          vertices[indices[i * 3 + 1] * 3],
          vertices[indices[i * 3 + 1] * 3 + 1],
          vertices[indices[i * 3 + 1] * 3 + 2]
        ),
        new AmmoLib.btVector3(
          vertices[indices[i * 3 + 2] * 3],
          vertices[indices[i * 3 + 2] * 3 + 1],
          vertices[indices[i * 3 + 2] * 3 + 2]
        ),
        false
      );
    }
    const shape = new AmmoLib.btConvexTriangleMeshShape(mesh, true, true);
    return shape;
  };
```
