### ISSUE TITLE
Odd behavior with passing a btVector3 as an argument to something that expects a float[]

### ISSUE THREAD

**Issue by InfiniteLee** [kripken/ammo.js#218]
This may be entirely my fault for setting up the IDL wrong, but here goes:

These two changes were recently added to the IDL:
```
interface btConvexHullShape {
  void btConvexHullShape([Const] optional float[] points, optional long numPoints);
...
interface btShapeHull {
  void btShapeHull(btConvexShape shape);
  boolean buildHull(float margin);
  long numVertices();
  long numTriangles();
  long numIndices();
  [Const] btVector3 getVertexPointer();
};
``` 

This is how they would get used in Bullet:
```
btConvexShape* originalConvexShape; is the original convexHullShape

	//create a hull approximation
	btShapeHull* hull = new btShapeHull(originalConvexShape);
	btScalar margin = originalConvexShape->getMargin();
	hull->buildHull(margin);
	btConvexHullShape* simplifiedConvexShape = new btConvexHullShape(hull->getVertexPointer(),hull->numVertices());
```
however, if you do the same in Ammo, it does something strange.
```
...
hullShape = new Ammo.btConvexHullShape(hull.getVertexPointer(), hull.numVertices());
```

The return value of `getVetexPointer()` is a btVector3.
However, Ammo.js has this definition for btConvexHullShape like so: 
```
function btConvexHullShape(arg0, arg1) {
  ensureCache.prepare();
  if (typeof arg0 == "object") {
    arg0 = ensureFloat32(arg0);
  }
...
```
And since `btVector3` is an object, `ensureFloat32` is called on it returning a seemingly arbitrary (but sometimes not entirely off) pointer into the heap. If `hull.getVertexPointer().ptr` is used instead, everything works as expected. The documentation for the webidl binder leads me to believe that this should not be the correct way to call this method, however.

My immediate thought was shouldn't the default behavior of this be to call `.ptr` on the object first? Or did I use the wrong return type for `getVertexPointer()` or the wrong argument type for the constructor of `btConvexHullShape`.

**Comment by kripken** [comment]
Hmm, how does this even compile in bullet? You can't pass a `btVector3*` where the receiving function expects `const btScalar*`. Unless there is some implicit cast going on? (If there is, ammo won't do it at runtime, we'd need to have a proper interface.)

**Comment by InfiniteLee** [comment]
I'm not sure- the c++ example is just something I found online.

**Comment by kripken** [comment]
Ah, in that case I'd bet it's either wrong or on another version of Bullet where the APIs were different.

**Comment by InfiniteLee** [comment]
It looks like this has mutated again as of emscripten 1.38.13 - `.ptr` is now `.a` - is that intentional?

**Comment by kripken** [comment]
Closure can minify `.ptr` to `.a`, but you should not be accessing that directly anyhow - what are you trying to achieve, and how?

**Comment by kripken** [comment]
Yes, getPointer is the safe way to get access to it, exactly.
