### ISSUE TITLE
Creating concave colliders from threejs geometry

### ISSUE THREAD

**Issue by precociousmouse** [kripken/ammo.js#248]
Hi all

I am trying to build a project using threejs and ammo, and I am trying to create a collider for a specific concave mesh (pic attached). I am trying to achieve this by pulling the geometry from the imported obj and generating a new collider mesh by writing the geometry into it. However I'm a little stuck what shape to use to copy the geometry into. btConvexHullShape seems to fill in the void (which I suppose logically it would do) and I can't seem to find any references to concave solvers. Is this a possible route to doing what I want to do or will I need to take an alternate approach?

cheers!

![pinball](https://user-images.githubusercontent.com/4642081/57612981-bfb97c00-756d-11e9-9065-96cdba48d96c.jpg)

**Comment by precociousmouse** [comment]
Hi all, as is typical I managed to solve the problem - After writing the triangle_mesh I passed it to a btBvhTriangleMeshShape which seems to work fine.

**Comment by Coder-345** [comment]
That's great I too face a similar issue . Could you share the code for reference which would be of huge help.
