### ISSUE TITLE
Pick up Objects Issue

### ISSUE THREAD

**Issue by jinkumak** [kripken/ammo.js#271]
Hi,
I try to pick up objects using a robot hand. 
But it's not working, 
If I try to pick up, the object didn't move up (friction not working properly)

![pickup](https://user-images.githubusercontent.com/26301861/62504687-9fc7ea80-b834-11e9-8ba1-7b9a5f0f1565.png)

is possible to pick up objects using three js+ammo js?
Thanks.

**Comment by kavikode** [comment]
I'm looking for a way to do this also. Can you please let me know if you follow the solution or workaround?

**Comment by bkhan23544** [comment]
Hi, did you find any solution?

**Comment by kavikode** [comment]
not yet. If you find anything let me know
