### ISSUE TITLE
btTransform operator* on btVector3 missing from IDL // cannot applyForce local/relative to btRigidBody

### ISSUE THREAD

**Issue by ricksterhd123** [kripken/ammo.js#277]
Been trying to applyForce relative to a rigidbody, if anyone has any ideas how I may do this then please let me know. Anyway, after trying to follow the solution from this ancient forum post: https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=2366 I've found this:

`btVector3 relativeForce = btVector3(0,10,0);`
`btTransform* boxTrans;`
`boxRigidBody->getMotionState()->getWroldTransform(boxTrans);`
`btVector3 correctedForce = (boxTrans * relativeForce) - boxTrans.getOrigin();`
`boxRigidBody->applyCentralForce(correctedForce);`

If you look in
https://pybullet.org/Bullet/BulletFull/classbtTransform.html
then you see that
btVector3 operator* (const btVector3 &x) const
is needed to achieve it, however i cannot find this definition in the IDL anywhere. 

Please could someone look into fixing this? Does anyone have an alternative solution, I just don't want to waste time migrating to another physics library...

**Comment by ricksterhd123** [comment]
For anyone looking how to apply a force local/relative to btRigidBody in ammo.js, here's how:
`let transform = new Ammo.btTransform();`
`body.getMotionState().getWorldTransform(transform);`
`let relativeForce = new Ammo.btVector3(0,0, 1000);`
`let relativeTransform = new Ammo.btTransform();`
`relativeTransform.setOrigin(relativeForce);`
`let relativeForce = (transform.op_mul(relativeTransform)).getOrigin();`
`body.applyForce(relativeForce, transform.getOrigin());`

Set the relativeForce which is a btVector3 into a btTransform using btTransform.setOrigin, then use op_mul and retrieve the resulting btVector3 using btTransform.getOrigin

I'm now going to close the issue, I hope people will find this if anyone has the same trouble I did.

**Comment by ricksterhd123** [comment]
So I tried to add this in the ammo.idl file but according to emscripten WebIDL binder has no support for Operator="*", any reason why?

**Comment by marlonicus** [comment]
Thanks @ricksterhd123! And thank you **again** for leaving a breadcrumb to this page on a 10-year-old forum thread, the internet needs more heroes like you 👏

**Comment by kmindspark** [comment]
Same here! Thanks @ricksterhd123

**Comment by AndreyNesterenko2020** [comment]
If you are using three JS, just do: 
`var temporaryEuler = new THREE.Vector3(1,0,0).applyQuaternion(objThree.quaternion);
objAmmo.setLinearVelocity(new Ammo.btVector3(temporaryEuler.x, temporaryEuler.y, temporaryEuler.z));`
Where `objAmmo` is the ammo object and `objThree` is the three js object.
The above code will make the object go forward. @ricksterhd123

**Comment by dataexcess** [comment]
@ricksterhd123 solution is not working for me. Seems I can only use setLinearVelocity. Which is not what I want, because then gravity is not working.
