### ISSUE TITLE
got runtime error when using worker

### ISSUE THREAD

**Issue by JayceLai** [kripken/ammo.js#290]
## detail
Just run wasm version of webgl_demo in chrome, then got below error.

## platform
- os: windows 10
- browser: chrome 80.0.3987.122(64 bit)

## console output

```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 2e 2e 2f 2e @+0). Build with -s ASSERTIONS=1 for more info.
```
## screenshot
![image](https://user-images.githubusercontent.com/23555101/75428804-b629c500-5983-11ea-9f1b-4f1c893bacc1.png)

**Comment by JayceLai** [comment]
btw, without using worker, run wasm version worked well

**Comment by lm165678** [comment]
> btw, without using worker, run wasm version worked well

Hi, have you solved it

**Comment by JayceLai** [comment]
😞, still no progress

**Comment by lm165678** [comment]
> 😞, still no progress

Hi, I have solved it. You need to use nginx proxy, and then add application / wasm wasm in the mime.types file of nginx; this line is enough. That's how I solved it. I hope I can help you.

**Comment by JayceLai** [comment]
Many thanks, I will try it later.
