### ISSUE TITLE
On the use of complex shape

### ISSUE THREAD

**Issue by lm165678** [kripken/ammo.js#291]
I don't know how to use btconvvextrianglemeshshape, bttrianglemeshshape and btbvhtrianglemeshshape on JS. Can you give me an example? Help me!!!

**Comment by lm165678** [comment]
I have solved it.

**Comment by Coder-345** [comment]
Can I know how you did that . I too have the same issue..

**Comment by willeastcott** [comment]
@Coder-345 You might find PlayCanvas' integration with ammo.js a useful reference:

https://github.com/playcanvas/engine/blob/master/src/framework/components/collision/system.js#L375
