### ISSUE TITLE
OOM on 1500 Boxes?

### ISSUE THREAD

**Issue by Pryme8** [kripken/ammo.js#296]
I am running just the default webGL demo and am running into 
```
ammo.js:73 Uncaught Error: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at pa (ammo.js:73)
    at emscripten_resize_heap (ammo.js:83)
    at Fb (ammo.js:53)
    at lf (ammo.js:25)
    at Array.Ty (ammo.js:57)
    at Array.Uy (ammo.js:53)
    at Kz (ammo.js:29)
    at Array.Gz (ammo.js:49)
    at Array.qz (ammo.js:53)
    at Array.pz (ammo.js:57)
```

So I split my buffers coming back into smaller chunks and tried that but am running into the same error.

Figured I should be able to handle more than 1500 boxes.  Prolly not an issue but I did see everyone else posting numbers like 7k objects and things like that so I figured there has to be something that can be done.

**Comment by willeastcott** [comment]
By default, I believe ammo allocates a memory pool of 64MB. With this default, around 1500 box bodies is roughly the limit. You can increase this size either by recompiling ammo or you can set some var to override the default size before ammo initializes (but I have to leave my computer for a bit so I can't look up those details for you right now)....

**Comment by Pryme8** [comment]
Yeah Ill look into that, I bet i can find it in the codebase if I search thank you!

**Comment by lm165678** [comment]
> Yeah Ill look into that, I bet i can find it in the codebase if I search thank you!

Hi, when you find a way to set the default memory size of the replacement, can you tell me, thank you.

**Comment by Pryme8** [comment]
https://github.com/kripken/ammo.js/blob/master/make.py

Line 76 I belive.
