### ISSUE TITLE
Question: Is Ammo.js using 32-bit floats? 

### ISSUE THREAD

**Issue by tgrajewski** [kripken/ammo.js#299]
This is a question, I don't know where to ask it, so maybe someone here will know.

Is Ammo.js using 32-bit floats internally for simulating physics? If yes, then is it possible to compile it with 64-bit doubles instead to increase accuracy? If yes, then has anyone did it already?

**Comment by kripken** [comment]
Look at `BT_USE_DOUBLE_PRECISION` which bullet uses in `btScalar.h`. You can flip it on to get doubles (the default is floats).

**Comment by kripken** [comment]
You will need to change the idl file, I believe, if you do that.

**Comment by tgrajewski** [comment]
Great, thanks!
