### ISSUE TITLE
Stage 4: Link make: error: unknown file type: glue.bc

### ISSUE THREAD

**Issue by gjmingsg** [kripken/ammo.js#301]
I build ammo.js in ubuntu 18.04, use emcc version 

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.13
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 9a39d5a2ecf7c9290d334f2697c3a4e533aa4bea)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by kripken** [comment]
It's possible you have an older `.bc` file from a previous compiler version. Try deleting it, or even doing `make clean` in `bullet/` (or just starting with a fresh checkout).

**Comment by gjmingsg** [comment]
thank your adivce,  pull a latest code and rebuild, and then fixed it
