### ISSUE TITLE
Ammo.btBvhTriangleMeshShape stopped working properly

### ISSUE THREAD

**Issue by tgrajewski** [kripken/ammo.js#302]
The latest commit 4aec847448ae302f7e1899bfefdfc018eacc20d4 has broken something, as my simulation stopped working properly. Collisions with `Ammo.btBvhTriangleMeshShape` aren't detected anymore, simulation runs fine, but triangle mesh is ignored. No warnings, no errors, running in browser, both ASM and WASM builds have the same issue.

Maybe too new Emscripten version was used to generate the build in the commit mentioned? I've attempted to build Ammo.js previous commit 85c0614cd5338aa0843814fe7bbd2df48164ece7 with the new Emscripten 1.38.12 and 1.38.14, but I have the same issue with `Ammo.btBvhTriangleMeshShape` being ignored in collisions.

**Comment by kripken** [comment]
cc @alexkowel who authored that commit

would be good to get a testcase @tgrajewski , as sounds like this might not be that commit, though, from the second paragraph?

**Comment by tgrajewski** [comment]
@kripken Unfortunately I don't have much time right now to make a test case, maybe later, sorry. 

To rephrase my issue differently:
* https://github.com/kripken/ammo.js/commit/85c0614cd5338aa0843814fe7bbd2df48164ece7 - The previous commit, all builds from the `build/` directory work fine for me.
* https://github.com/kripken/ammo.js/commit/85c0614cd5338aa0843814fe7bbd2df48164ece7 - Trying to compile myself the same version with Emscripten 1.38.12 on Windows Subsystem for Linux (Ubuntu 20) breakes the `btBvhTriangleMeshShape` for me, the shape is ignored in collisions.
* https://github.com/kripken/ammo.js/commit/4aec847448ae302f7e1899bfefdfc018eacc20d4 - The latest commit, both pre-built version from the `build/` directory and one compiled myself also breaks `btBvhTriangleMeshShape`.

Maybe someone else will diagnose the issue and find a solution in the mean time.

**Comment by alexkowel** [comment]
That's strange because we use btBvhTriangleMeshShape extensively in Verge3D. Let me check.

**Comment by alexkowel** [comment]
Both wasm and regular builds work fine for me. I used Emscripten 1.39.12 on Fedora Linux to compile them.
BTW how do you initialize btBvhTriangleMeshShape()? Can you provide a code example so I could reproduce the issue?

**Comment by tgrajewski** [comment]
@alexkowel Below is my code that creates a `btBvhTriangleMeshShape` instance. I first build a `btTriangleMesh` from individual triangles, calculating AABB along the way.

```javascript
var minX = Infinity, minY = Infinity, minZ = Infinity;
var maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
var mesh = new Ammo.btTriangleMesh();
for (var i = 0; i < triangles.length; i++) {
    var x0 = triangles[i][0][0] * scale, y0 = triangles[i][0][1] * scale, z0 = triangles[i][0][2] * scale;
    var x1 = triangles[i][1][0] * scale, y1 = triangles[i][1][1] * scale, z1 = triangles[i][1][2] * scale;
    var x2 = triangles[i][2][0] * scale, y2 = triangles[i][2][1] * scale, z2 = triangles[i][2][2] * scale;

    minX = Math.min(minX, x0, x1, x2);
    minY = Math.min(minY, y0, y1, y2);
    minZ = Math.min(minZ, z0, z1, z2);
    maxX = Math.max(maxX, x0, x1, x2);
    maxY = Math.max(maxY, y0, y1, y2);
    maxZ = Math.max(maxZ, z0, z1, z2);

    mesh.addTriangle(
        new Ammo.btVector3(x0, y0, z0),
        new Ammo.btVector3(x1, y1, z1),
        new Ammo.btVector3(x2, y2, z2));
}

var shape = new Ammo.btBvhTriangleMeshShape(
    mesh, true, new Ammo.btVector3(minX, minY, minZ), new Ammo.btVector3(maxX, maxY, maxZ), true);
// if (boardMargin !== -1)
//     shape.setMargin(boardMargin);

var board = new Ammo.btRigidBody(new Ammo.btRigidBodyConstructionInfo(0, null, shape));
board.setFriction(0.25);
board.setRestitution(0.2);
world.addRigidBody(board);
```

**Comment by willeastcott** [comment]
In case it helps, [here's the PlayCanvas code](https://github.com/playcanvas/engine/blob/master/src/framework/components/collision/system.js#L394) to create a `btBvhTriangleMeshShape`.

We don't pass the 3rd, 4th and 5th parameters. I don't even see those as being valid parameters in the IDL:

https://github.com/kripken/ammo.js/blob/master/ammo.idl#L467

Maybe parameter 3 is being cast to `true`.

BTW, you shouldn't just call new on Ammo objects (like with those `btVector3` instances and throw them away. Always `Ammo.destroy` whatever you `new` or you'll leak memory.

**Comment by tgrajewski** [comment]
@willeastcott I took the arguments from the Bullet manual: https://pybullet.org/Bullet/BulletFull/classbtBvhTriangleMeshShape.html

What's interesting is that I actually used Ammo build from PlayCanvas repository and it worked with those extra arguments. Anyway, removing those extra arguments from my code fixes the issue, thanks!

**Comment by tgrajewski** [comment]
> BTW, you shouldn't just call new on Ammo objects (like with those btVector3 instances and throw them away. Always Ammo.destroy whatever you new or you'll leak memory.

@willeastcott Can you tell me more about this? I'm passing those btVector3 instances and Ammo doesn't actually keep them as references? I'm not familiar with WASM, so any help very welcome!

Should I do something like that:
```javascript
    var v0 = new Ammo.btVector3(x0, y0, z0);
    var v1 = new Ammo.btVector3(x1, y1, z1);
    var v2 = new Ammo.btVector3(x2, y2, z2);

    mesh.addTriangle(v0, v1, v2);

    v0.destroy();
    v1.destroy();
    v2.destroy();
```

**Comment by willeastcott** [comment]
@tgrajewski Yep, exactly! 😄 But since you'll call `addTriangle` many times, typically, you would reuse `v0`, `v1` and `v2` for all calls to `addTriangle` and destroy them when you're done.

**Comment by tgrajewski** [comment]
OK, great, thank you for your time, it helped me a lot!
