### ISSUE TITLE
How to detect if two bodies collide?

### ISSUE THREAD

**Issue by tgrajewski** [kripken/ammo.js#303]
How to add a callback when two bodies collide, for example to play sound effects?

Is making a custom build required, as described in https://github.com/kripken/ammo.js/pull/251?

**Comment by willeastcott** [comment]
You might be interested to check out how [PlayCanvas](https://github.com/playcanvas/engine) does this. In particular, you should use `setInternalTickCallback`:

https://github.com/playcanvas/engine/blob/master/src/framework/components/rigid-body/system.js#L184

And then process the manifolds:

https://github.com/playcanvas/engine/blob/master/src/framework/components/rigid-body/system.js#L545

**Comment by tgrajewski** [comment]
@willeastcott Thank you for the hint! I will not only use the approach from PlayCanvas, but also their Ammo build, as it contains the `Ammo.addFunction` method that is missing here and I seem to fail to compile Ammo properly myself.

**Comment by jespertheend** [comment]
If anyone stumbles upon this, more info about `addFunction` [here](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-javascript-functions-as-function-pointers-from-c). You need to provide a second argument with a signature. You can use `Ammo.CONTACT_PROCESSED_CALLBACK_SIGNATURE` as second argument for example. The function returns a pointer that you can pass into `dynamicsWorld.setContactProcessedCallback`. There's a javascript example in #251.
