### ISSUE TITLE
TypeError: Promise is not a constructor while testing ammo js after compiling

### ISSUE THREAD

**Issue by wenyangchu** [kripken/ammo.js#305]
Hi guys, I tried to update/add some bullet physics module to AMMO. So the first step is to compile the latest AMMO but I have an issue right away. When I try the python test.py I have this weird error:

"TypeError: Promise is not a constructor". Does anyone know why this happens?

The following is my environment to reproduce it and output:
***********************
Environment:

Ubuntu 18.04
Emscripten 1.39.16
Node 12.9.1 64 bit

./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh

python make.py
python test.py

Output: *************************************************

Using build: builds/ammo.js
/home/bence/emsdk/node/12.9.1_64bit/bin/node

*===================================
['/home/bence/emsdk/node/12.9.1_64bit/bin/node']
*===================================

0 : regression tests
      basics.js
('/home/bence/emsdk/node/12.9.1_64bit/bin/node t.js', 'in', '/home/bence/ammo.js/builds')
/home/bence/ammo.js/builds/t.js:11
var Module=typeof Ammo!=="undefined"?Ammo:{};var readyPromiseResolve,readyPromiseReject;Module["ready"]=new Promise(function(resolve,reject){readyPromiseResolve=resolve;readyPromiseReject=reject});var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirec

TypeError: Promise is not a constructor
    at /home/bence/ammo.js/builds/t.js:11:105
    at Object.<anonymous> (/home/bence/ammo.js/builds/t.js:98:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    assert 'ok.' in output, output
AssertionError

**Comment by kripken** [comment]
That's possibly the MODULARIZE changes mentioned in the emscripten changelog, https://github.com/emscripten-core/emscripten/blob/master/ChangeLog.md#13916-05152020

We may need to update something here for that. As mentioned in the changelog, building with ASSERTIONS may help figure this out.

**Comment by wenyangchu** [comment]
Unfortunately, I build with ASSERTIONS=1 but I do not see anything extra. Did I do anything wrong?

================
Stage 5: emcc: -O3 --llvm-lto 1 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=["UTF8ToS                                                        tring"] -s ASSERTIONS=1 -s WASM=0 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s                                                         SINGLE_FILE=1 -s LEGACY_VM_SUPPORT=1 -s NO_DYNAMIC_EXECUTION=1 -s TOTAL_MEMORY=67108864 -s EXPORT_NAME="Ammo"                                                         -s MODULARIZE=1
=============================================================================================================                                                        =============================================================================================================                                                        =============================================================================================================                                                        ================

emcc:WARNING: --llvm-lto ignored when using llvm backend
emcc: warning: for wasm there is no need to set ELIMINATE_DUPLICATE_FUNCTIONS, the binaryen optimizer does it                                                         automatically [-Wemcc]

=============
Stage 6: wrap
=============

**Comment by wenyangchu** [comment]
Thanks for the suggestions. Since you mentioned there is a possible issue in the latest emscripten. I switched to earlier version 1.39.0 and another version 1.39.5(not 100%sure). both of them have issues and compiling failed. I switch back to the latest version and compiled again. The "Promise" disappeared and test past. I do not understand why this is the case.

**Comment by wenyangchu** [comment]
I think I will close the issue now. Once I see some issue again and reproducible, I will reopen this issue.
