### ISSUE TITLE
make.py error: no attribute 'Building' in emscripten's tools/shared.py

### ISSUE THREAD

**Issue by BradDunagan** [kripken/ammo.js#315]
Just cloned ammo.js an hour ago.

Did a pull for the latest emscripten tools.

Get this error in make.py -

    Exception has occurred: AttributeError
    'module' object has no attribute 'Building'
      File "/home/brad/dev/ammo.js/make.py", line 137, in build
        emscripten.Building.emcc('glue.cpp', args, 'glue.o')
      File "/home/brad/dev/ammo.js/make.py", line 194, in <module>
        build()

The erroneous line is -

        emscripten.Building.emcc('glue.cpp', args, 'glue.o')

emscripten is a module imported like so -

      import tools.shared as emscripten

It appears the correct module is being imported because the debugger says this -

    <module 'tools.shared' from '/home/brad/dev/emsdk/upstream/emscripten/tools/shared.pyc'>

I look at shared.py and can not find a 'Building' attribute.

Should I maybe be using a specific version of emscripten?

**Comment by kripken** [comment]
I think we need to update the script here, yeah. `tools.shared.Building` is now `tools.building` I believe. A PR to fix this would be great!

**Comment by BradDunagan** [comment]
Fixed #316
