### ISSUE TITLE
A strange thing happened when I used btBvhTriangleMeshShape

### ISSUE THREAD

**Issue by OliverXH** [kripken/ammo.js#339]
I use ammo.js inthree.js.

I have a box and I use `Ammo.btBvhTriangleMeshShape()` to add collision shape for it, but in the physical world, it seems like it 
 cannot rotate. It looks like this (Normally, the box rotates clockwise):

![2020-10-11_140809](https://user-images.githubusercontent.com/49978259/95671567-4216f700-0bcb-11eb-8a0c-1dae02f35be4.png)

![8ee0e901-a08c-662e-2a03-62a7f085b6f3](https://user-images.githubusercontent.com/49978259/95671600-ab970580-0bcb-11eb-9e06-ce5889910c42.gif)

I want to know if I'm wrong, or whether it's just the way it is. If I am wrong, how can I correct it?

**Comment by willeastcott** [comment]
Hi. I don't really know anything about three.js - I only know about PlayCanvas. But PlayCanvas does rely on `btBvhTriangleMeshShape`:
 
https://github.com/playcanvas/engine/blob/master/src/framework/components/collision/system.js#L410

The only explanation for what you're seeing that I can think of is that the angular factor of the body is set to `0, 0, 0`. Could you check your code for that?

**Comment by OliverXH** [comment]
@willeastcott 
Thanks for your help, I found the solution from the code which you provided.

In my previous code, I directly used `btBvhTriangleMeshShape` as the collision shape of the rigid body. After seeing the code you provided, I used `btCompoundShape` as the direct collision shape of the rigid body and added `btBvhTriangleMeshShape` to `btCompoundShape`. After running it again, box rotated normally.

**Comment by OliverXH** [comment]
@willeastcott Another thing happened, there couldn't be collisions between two btBvhTriangleMeshShape
![a3db7517-2e5a-9480-91ac-c6ec1ec99aeb](https://user-images.githubusercontent.com/49978259/95726919-19b2f980-0cac-11eb-884d-61bda265269f.gif)

![1ced0e65-5527-0385-b16a-9217a44632da](https://user-images.githubusercontent.com/49978259/95729107-f50c5100-0cae-11eb-8c47-1c37d2d9d88e.gif)

**Comment by aruljobin** [comment]
@OliverXH  Did you get a solution for - collisions between two btBvhTriangleMeshShap? 
If yes, Please share the steps to achieve it.

**Comment by OliverXH** [comment]
@aruljobin 

It seems that `btBvhTriangleMeshShap`  only be used on passive objects, not on moving objects.

For active objects, I think the only way is to use `btGImpactMeshShape`. But it seems that Ammo.js does not have this class.

**Comment by aruljobin** [comment]
Oh!!
@OliverXH @willeastcott  @kripken  Can you suggest me anything to get the collision between two teeth(upper arch/lower arch)?

**Comment by lo-th** [comment]
btBvhTriangleMeshShap is for static object 
but you can use Ammo.btConvexHullShape for moving object 
only is your object is convex

**Comment by OliverXH** [comment]
@aruljobin I added `btGImpactMeshShape` to my ammo.js Repo, and rebuild it, now you can use it to make sure multiple dynamic rigidbody with mesh collision shape can collide with each other.

Here is the [example](https://oliverxh.github.io/demo/gimpact.html)
