### ISSUE TITLE
Inconsistent IDL logic/standards

### ISSUE THREAD

**Issue by mundusnine** [kripken/ammo.js#342]
In the emscripten [docs](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#pointers-references-value-types-ref-and-value) its says:
```
Undecorated argument and return values in the IDL are assumed to be pointers in the C++:
```
Considering in the IDL we have:
![image](https://user-images.githubusercontent.com/29337013/99090956-38ebc200-259d-11eb-84e4-0c3b1eac62ac.png)

I would expect the cpp to return a void*. But we have:
![image](https://user-images.githubusercontent.com/29337013/99091043-56209080-259d-11eb-9884-827e0c6e6458.png)

Is this an issue in the docs ? Did the logic change ? I am making an IDL parser and I would like to follow a standard method of working but things seem inconsistent.

I understand that adding `[Value]` to all return values would be nuisance so that's probably why this standard in the docs isn't followed.

**Comment by kripken** [comment]
Things like void, integers, etc., translate normally. So a void for the return in both places is expected. That comment is meant to say that for things like a `btVector3`, if it is not decorated to say more about what it is, then it is a pointer.

A PR to improve the emscripten docs would be appreciated if you have an idea for a better explanation (my english is not great personally).

**Comment by mundusnine** [comment]
Closed by: https://github.com/emscripten-core/emscripten/pull/12773
