### ISSUE TITLE
How to integrate?

### ISSUE THREAD

**Issue by Dev-MarkoF** [kripken/ammo.js#344]
A bit of a noob question maybe, but i'm coming from c# and i'm a little rusty on javascript/typescript.

I want to integrate ammo.js in a small game engine, in the end result ammo should be hidden within it. I did that with Oimo Physics but to be honest it lacks the quality of ammo, so i wanted to switch.

Now the problem is that ammo needs to wrap every code within 
**Ammo().then(function(Ammo){**
   //all game code, not only physics but also visuals and stuff
**});**

Can i somehow avoid this? Or stop any execution of anything else until ammo is really ready.
I tried workarounds like loading all my game engine files within the Ammo().then, but that results in a Javascript-Promise rejection.

**I need the functionality that users just write code in the style of the game engine and never have to wrap anything around that.**

So they can just code something like without any wrapper:
physics.initialize();   //ammo world is created in the background, 
gameobject.addRigidbody(mass, box);  //ammo body is created in the background

Thanks in advance. I looked at implementations of babylon.js and playcanvas they seem to use a much older ammo version, without javascript-promise.

If it helps i use **ammo.js not wasm** or anything modern module related, the game should run locally with plain javascript.

**Comment by giniedp** [comment]
> Can i somehow avoid this? Or stop any execution of anything else until ammo is really ready.

That is something Ammo can not solve for you. You need some kind of a bootstrapping process for your engine. There are many ways to do it.

You could have one `main` or `run` function in your engine/application to actually start execution. Unless execution is not started no physics related code should run, so you can load all your engine scripts before launching Ammo. Then initialize Ammo and start execution when it is ready

```js
Ammo(Ammo).then(function () {
  main() // start execution
})
```

here is an example of exactly that technique https://stackblitz.com/edit/ammojs-typed-falling-cubes

**Comment by willeastcott** [comment]
In case it helps @Dev-MarkoF, ammo.js is tightly integrated into PlayCanvas. So it might be interesting to you to see how we leverage it: https://github.com/playcanvas/engine

**Comment by Dev-MarkoF** [comment]
Thanks a lot, @giniedp that looks really promising, i thought i had set up a system like that and it did not work, but i might have overlooked something. Your example should help me to sort that out.

I know that it's not a ammo problem, but a problem i only got in conjuncture with using ammo, so this was the best place to ask.
