### ISSUE TITLE
How to add btInternalEdgeUtility and btTriangleInfoMap

### ISSUE THREAD

**Issue by RomanCood** [kripken/ammo.js#367]
Hi,

I want to use functions (btAdjustInternalEdgeContacts, btGenerateInternalEdgeInfo) from the btInternalEdgeUtility.cpp.
Unfortunately, they are not included in the ammojs build.

I tried to include it myself, but the ammo.idl file can only accept classes, since btInternalEdgeUtility exports functions, I'm not able to include it there.
Is there anywhere else that I can put it in ?

How can I include it ? Can someone explain to me how it works ? 

Thanks in advance

**Comment by wissem-cood** [comment]
@kripken Hey, any new about this topic ?

**Comment by kripken** [comment]
In general, WebIDL handles classes, yes. For global functions, you'd need to create a class in C++ that calls those functions (a "global scope accessor class", sort of). Then use WebIDL on that class.

**Comment by wissem-cood** [comment]
Okay, so i tried again, followed what you said.
Seems to work, build passes, i'll try this tomorrow, ( it's pretty late in here haha ^^' ), i'll keep you updated, here what i've done:

Created the cpp class -> btCustomClass :
![Screenshot from 2021-05-11 01-21-07](https://user-images.githubusercontent.com/76944578/117736946-1c051400-b1f9-11eb-8ed0-50bff3848659.png)

Then created the declaration file :
![Screenshot from 2021-05-11 01-21-18](https://user-images.githubusercontent.com/76944578/117736957-20c9c800-b1f9-11eb-9854-9febde34d835.png)

Added it in the ammo.idl
![Screenshot from 2021-05-11 01-25-07](https://user-images.githubusercontent.com/76944578/117736969-24f5e580-b1f9-11eb-9d47-81942411b41c.png)

also added it in the btBulletCollisionCommon.h :
![Screenshot from 2021-05-11 01-36-33](https://user-images.githubusercontent.com/76944578/117737080-5d95bf00-b1f9-11eb-86d4-111fb4509824.png)

And finaly added the cpp + .h in the CMakeLists.txt inside the bullet collision folder:
![Screenshot from 2021-05-11 01-37-57](https://user-images.githubusercontent.com/76944578/117737193-9d5ca680-b1f9-11eb-9941-d0f522e51bac.png)

I then, did " docker-compose up" and it worked fine, now i can access this class.. i'll tell you tomorrow if everything is working fine!

**Comment by RomanCood** [comment]
So we managed to add our class in C ++ which contains all these global functions.
To correct this jitter/bumpy problem (which is due to friction and restitution / bouncing), we had to modify the CustomMaterialCombinerCallback function because those given in the examples are no longer good.

Here is our custom class: 
![image](https://user-images.githubusercontent.com/58509533/125753807-099a571a-f9b6-4397-badb-c0d80da7b14c.png)

and our code: 
![image](https://user-images.githubusercontent.com/58509533/125753844-630c4016-b0f6-4deb-b4f7-291b66eb04d1.png)

Do not forget to use the CF_CUSTOM_MATERIAL_CALLBACK flag with the rigidbody
![image](https://user-images.githubusercontent.com/58509533/125753878-d86faee5-7e12-4d45-b99f-77eb493e3df1.png)

**Comment by wissem-cood** [comment]
Hey again,

Important thing to mention, don't forget to tweak the value of the ▶️ **Margin & Friction** ◀️ !
These are important to reduce the amount of bumpiness !

Actually we set it as follows :
➡️ this.rigidBody.setFriction(0.5); _Increase this value to make it less slippery_
➡️ this.shape.setMargin(0.55); _You need to change this value, to find something that fits your needs_

Hope it helps ❤️
