### ISSUE TITLE
AllHitsRayResultCallback is missing members

### ISSUE THREAD

**Issue by daredevildave** [kripken/ammo.js#37]
`AllHitsRayResultCallback` has arrays of collision objects, and hit points/normals, instead of the single values like `ClosestRayResultCallback`.

It seems like they are missing in Ammo.js and you just get access to the values inherited from  `RayResultCallback`.

Missing values:

`m_collisionObjects`
`m_hitPointWorld`
`m_hitNormalWorld`
`m_hitFractions`

**Comment by willeastcott** [comment]
This was fixed by the following PR: https://github.com/kripken/ammo.js/pull/276

@kripken - feel free to close this.

**Comment by kripken** [comment]
Thanks, closing.
