### ISSUE TITLE
btCollisionWorld.removeCollisionObject does not work

### ISSUE THREAD

**Issue by kaphula** [kripken/ammo.js#388]
Hello,

Can anyone confirm that `btCollisionWorld.removeCollisionObject` is working properly in ammo.js? When I call this method my simulation breaks. Further more, reading the source code of bullet reveals that many bullet functions call `btAssert(...)` internally. I could not figure out what does that internal assert do if it gets executed. Does it crash bullet or just exit the current function that is being executed? Is it possible to get errors or warnings generated by bullet to the javascript side?

**Comment by Oxynt** [comment]
Work fine, here is my code.
Depending how Bullet calculate your collision, some infos stay in memory.
The cleanest answer I found was to delete the RigidBody reference too.
```
//set world
const world = new AmmoLib.btDiscreteDynamicsWorld(dispatcher, broadphase, solver, collisionConfiguration);

//main code here....

//remove collision on object
world.removeCollisionObject(body);
world.removeRigidBody (body);
```

**Comment by kaphula** [comment]
Thank you, yeah I accidentally misunderstood the functionality of `btCollisionWorld.removeCollisionObject`. I thought `removeCollisionObject` and `addCollisionObject` were functions for setting an already added object's collision filter values separately. But it seems there's no way to dynamically alter the collision filter settings (group / mask) once an object has been added to a physics world.
