### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by griffi-gh** [kripken/ammo.js#390]
I cant import Ammo using ES6 `import`  
  
I tried: 
1) `import Ammo from './lib/ammo.wasm.js'` (import not found: default)  
2) `import * as Ammo from './lib/ammo.wasm.js'` (returns empty object)
3) `import './lib/ammo.wasm.js'` (i expected Ammo to be a global variable)

**Comment by alizayan684** [comment]
Can you please explain how you solved this problem? I am having this issue
