### ISSUE TITLE
Setting additional attributes of btRigidBodyConstructionInfo (friction,restitution,damping)

### ISSUE THREAD

**Issue by honzasusek** [kripken/ammo.js#72]
Is it possible in the current version? There are no methods associated with this in bullet and settings the variables in javascript does not seem to do anything.

**Comment by samvv** [comment]
@honzasusek Did you solve this? If so, could you explain how?

**Comment by samvv** [comment]
It seems that there are accessors available which are prepended with `get_`. Will try to confirm later this day.
