### ISSUE TITLE
ContactResultCallback not subclassable

### ISSUE THREAD

**Issue by Doidel** [kripken/ammo.js#75]
For contactTest (http://www.bulletphysics.org/mediawiki-1.5.8/index.php/Collision_Callbacks_and_Triggers#contactTest) I need to extend the abstract class ContactResultCallback. It isn't subclassable though. Can you `allow_subclass` it so we can use the contact tests?

Thanks!

PS: abstract methods reference ( just fyi, I know you don't need it x/ ): http://kripken.github.io/emscripten/docs/coding/connecting_cpp_and_javascript/embind.html?highlight=abstract#abstract-methods

**Comment by a735561656** [comment]
I meet the same question with you . Did you solve it? Can you give me some help? Thanks!

**Comment by a735561656** [comment]
My Email is 735561656 @  qq.com
