### ISSUE TITLE
Soft bodies?

### ISSUE THREAD

**Issue by josephrocca** [kripken/ammo.js#83]
Hi, I originally asked this [on stackoverflow](http://stackoverflow.com/questions/25581159/3d-soft-body-physics-with-ammo-js) and was directed here (if it's not an appropriate question here it would be great if you could answer it on SO):

I'm told that soft body physics wasn't ported over to Ammo.js. So a few questions:
- Why? Would it be too computationally intensive for JavaScript?
- Are there any JavaScript builds which include the soft body physics part of the Bullet engine?
- Is Bullet's soft body physics reliable enough for me to be attempting to play around with a JavaScript version?

Actually, all I need is simple soft-body cubes that can connect to each other (maybe there's a simple hacky way to do this?)

Thanks a heap,
Joe

**Comment by hellofunk** [comment]
@josephrocca did you try your spring and masses approach? I did not know that spring constraints were supported in ammo. How did it work out?

**Comment by Kagetsuki** [comment]
It appears this has been implemented?
EG: http://kripken.github.com/ammo.js/examples/webgl_demo_softbody_volume/index.html
This issue should probably be closed?

**Comment by kripken** [comment]
Yes, thanks @Kagetsuki
